export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER_SUCCUSS = "AUTH_REGISTER_SUCCUSS";
export const AUTH_lOGIN_SUCCUSS = "AUTH_lOGIN_SUCCUSS";
export const GOOGLE_SIGNUP = "GOOGLE_SIGNUP";
export const GOOGLE_SIGNIN = "GOOGLE_SIGNIN";
export const GOOGLE_SIGNUP_SUCCUSS = "GOOGLE_SIGNUP_SUCCUSS";
export const GOOGLE_SIGNIN_SUCCUSS = "GOOGLE_SIGNIN_SUCCUSS";
export const ERROR = "ERROR";
export const GET_PAPER_BY_ID = "GET_PAPER_BY_ID";
export const GET_PAPER_BY_ID_SUCCESS = "GET_PAPER_BY_ID_SUCCESS";
export const CREATE_QUESTIONS = "CREATE_QUESTIONS";
export const CREATE_QUESTIONS_SUCCESS = "CREATE_QUESTIONS_SUCCESS";
export const GET_ALL_QUESTION = "GET_ALL_QUESTION";
export const GET_ALL_QUESTION_SUCCESS = "GET_ALL_QUESTION_SUCCESS";
export const CREATE_QUESTION_PAPER = "CREATE_QUESTION_PAPER";
export const CREATE_QUESTION_PAPER_SUCCESS = "CREATE_QUESTION_PAPER_SUCCESS";
export const USER_SUBMIT_PAPER = "USER_SUBMIT_PAPER";
export const USER_SUBMIT_PAPER_SUCCESS = "USER_SUBMIT_PAPER_SUCCESS";
export const GET_ALL_PAPERS = "GET_ALL_PAPER";
export const GET_ALL_PAPERS_SUCCESS = "GET_ALL_PAPER_SUCCESS";
export const GET_USER_RESULT = "GET_USER_RESULT";
export const GET_USER_RESULT_SUCCESS = "GET_USER_RESULT_SUCCESS";
export const GET_ALL_USER_RESULT = "GET_ALL_USER_RESULT";
export const GET_ALL_USER_RESULT_SUCCESS = "GET_ALL_USER_RESULT_SUCCESS";
export const DELETE_QUESTIONS = "DELETE_QUESTIONS";
export const DELETE_QUESTIONS_SUCCESS = "DELETE_QUESTIONS_SUCCESS";

//   =========================Skill=====================================
export const CREATE_SKILL = "CREATE_SKILL";
export const CREATE_SKILL_SUCCESS = "CREATE_SKILL_SUCCESS";
export const GET_SKILL = "GET_SKILL";
export const GET_SKILL_SUCCESS = "GET_SKILL_SUCCESS";
export const GET_ALL_QUESTIONS_BY_SKILL = "GET_ALL_QUESTIONS_BY_SKILL";
export const GET_SKILL_ID = "GET_SKILL_ID";
export const GET_ALL_QUESTIONS_BY_SKILL_SUCCESS =
  "GET_ALL_QUESTIONS_BY_SKILL_SUCCESS";
